apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Abdu\desktop\finalapi\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
