version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  api:
    build: .
    ports: 
      - 8082:8082
    environment:
      MONGO_URI: mongodb://mongodb_container
      DB: TestDB 
      PORT: 8082
    depends_on: 
      - mongodb_container
volumes:
  mongodb_data_container:
