apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Abdu\desktop\finalapi\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-container
  name: mongodb-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-container
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Abdu\desktop\finalapi\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-container
    spec:
      containers:
        - image: mongo:latest
          name: mongodb-container
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data-container
      restartPolicy: Always
      volumes:
        - name: mongodb-data-container
          persistentVolumeClaim:
            claimName: mongodb-data-container
status: {}
