apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Abdu\desktop\finalapi\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-container
  name: mongodb-container
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongodb-container
status:
  loadBalancer: {}
